fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_security_login:
  path: /mon-compte/connexion
  controller: fos_user.security.controller:loginAction
  methods: [GET, POST]

fos_user_security_check:
  path: /login_check
  controller: fos_user.security.controller:checkAction
  methods: [POST]

fos_user_security_logout:
  path: /mon-compte/deconnexion
  controller: fos_user.security.controller:logoutAction
  methods: [GET, POST]

fos_user_profile:
  resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
  prefix:
    fr: /{_locale}/mon-compte/profil
    en: /{_locale}/my-account/profile
    es: /{_locale}/mi-cuenta/perfil

fos_user_register:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix:
    fr: /{_locale}/inscription
    en: /{_locale}/registration
    es: /{_locale}/inscripcion

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
  prefix: /mon-compte/reinitialiser

fos_user_change_password:
  resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
  prefix: /mon-compte/profil
